name: Merge Check Jest CI

on: 
  pull_request:
    branches:
      - main # 这里指定要检查的目标分支

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'yarn'
      - run: echo '安装依赖'
      - run: yarn install --frozen-lockfile
      - run: echo '检查源码编译是否正常'
      - run: yarn run build
      - run: echo '检查单元测试是否正常'
      - run: yarn run test
      